model:
  class_name: model.LVSM_scene_decoder_only.Images2LatentScene

  image_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 9  # 3 RGB + 3 direction + 3 Reference

  target_pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6  # 3 direction + 3 Reference
  transformer:
    d: 768
    d_head: 64
    n_layer: 6
    special_init: true
    depth_init: true
    use_qk_norm: true

diffusion:
  num_train_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"


training:
  amp_dtype: bf16
  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 16
  beta1: 0.9
  beta2: 0.95
  allowed_gradnorm_factor: 5
  center_crop: true
  scene_scale_factor: 1.35
  checkpoint_dir: ./experiments/checkpoints/Mini_chunked_LVSM_test_extrapol_on
  dataset_name: data.dataset_scene.Dataset
  dataset_path: ./datasets/re10k_test_chunks_all_views
  grad_accum_steps: 4
  grad_checkpoint_every: 1
  grad_clip_norm: 1.0


  l2_loss_weight: 1.0
  lpips_loss_weight: 0.0
  perceptual_loss_weight: 0.5

  lr: 0.0004
  train_steps: 500000


  num_input_views: 4
  num_target_views: 8
  num_threads: 8
  num_views: 12
  num_workers: 4
  prefetch_factor: 32
  print_every: 20
  square_crop: true
  
  
  #custom stuff
  uniform_crop_size: False  # FALSE IS ORIGINAL LVSM BEHAVIOUR - TRUE IS FOR NEW DATASETS THAT DO NOT HAVE SAME ASPECT RATIO
  random_sample_views: True 
  # FALSE IS ORIGINAL LVSM BEHAVIOUR - TRUE MEANS WE RANDOMLY SAMPLE VIEWS - IN FALSE WE ONLY TAKE TARGET VIEWS IN BETWEEN THE INPUT VIEWS
  variable_amount_of_views: False 
  # FALSE IS ORIGINAL LVSM BEHAVIOUR - False means we use default viewcount - whats in the config - with True we regenerate amount of views for each batch
  use_diffusion: False
  # False means we use the original LVSM behaviour - True means we use diffusion to generate

  target_has_input: true
  use_amp: true
  use_rel_pose: false
  use_tf32: true
  view_selector:
    max_frame_dist: 192
    min_frame_dist: 25
  vis_every: 1000
  wandb_exp_name: Mini_chunked_LVSM_test_extrapol_on
  wandb_log_every: 50
  
  wandb_project: LVSM
  warmup: 3000
  weight_decay: 0.05


# inference / evaluation
inference:
  if_inference: False
  compute_metrics: False
  view_idx_file_path: ./data/evaluation_index_re10k.json
  render_video: False
  render_video_config:
    traj_type: interpolate
    num_frames: 60
    loop_video: True 
    order_poses: False

  