model:
  class_name: model.LVSM_scene_decoder_only.Images2LatentScene

  image_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 9  # 3 RGB + 3 direction + 3 Reference

  target_pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6  # 3 direction + 3 Reference
  transformer:
    d: 768
    d_head: 64
    n_layer: 6
    special_init: true
    depth_init: true
    use_qk_norm: true

training:
  amp_dtype: bf16
  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 16
  beta1: 0.9
  beta2: 0.95
  allowed_gradnorm_factor: 5
  center_crop: true
  scene_scale_factor: 1.35
  checkpoint_dir: ./experiments/checkpoints/LVSM_co3d_scene_decoder_only
  checkpoint_every: 2000
  dataset_name: data.dataset_scene.Dataset
  dataset_path: ./datasets/co3d_index/full_list.txt
  grad_accum_steps: 4
  grad_checkpoint_every: 1
  grad_clip_norm: 1.0


  l2_loss_weight: 1.0
  lpips_loss_weight: 0.0
  perceptual_loss_weight: 0.5

  lr: 0.0004
  train_steps: 1000000


  num_input_views: 2
  num_target_views: 6
  num_threads: 8
  num_views: 8
  num_workers: 4
  prefetch_factor: 32
  print_every: 20


  square_crop: true
  uniform_crop_size: True  # FALSE IS ORIGINAL LVSM BEHAVIOUR - TRUE IS FOR NEW DATASETS THAT DO NOT HAVE SAME ASPECT RATIO
  target_has_input: true
  use_amp: true
  use_rel_pose: false
  use_tf32: true
  view_selector:
    max_frame_dist: 192
    min_frame_dist: 25
  vis_every: 1000
  wandb_exp_name: co3d_LVSM_scene_decoder_only
  wandb_log_every: 50
  
  wandb_project: LVSM
  warmup: 3000
  weight_decay: 0.05


# inference / evaluation
inference:
  if_inference: False
  compute_metrics: False
  view_idx_file_path: ./data/evaluation_index_re10k.json
  render_video: True
  render_video_config:
    traj_type: interpolate
    num_frames: 60
    loop_video: True 
    order_poses: False

  